<?php
namespace carlosllorca\hl7messages\Scenarios;
use yii\base\Model;
use yii\bootstrap\ActiveForm;
use yii\db\ActiveRecord;
use carlosllorca\hl7messages\Segments;
use carlosllorca\hl7messages\Scenarios;
use carlosllorca\hl7messages\Segments\PidSegment;
use carlosllorca\hl7messages\Segments\Nk1Segment;
use yii\base\Exception;

/**
 * @property PidSegment $pid 
 * @property Nk1Segment $nk1[] 
 * @property Nk1Segment $nk1_temp;
 * @property Vaccines $vaccines[]
 * @property Vaccines $temp_vaccine
 *
 */
class Immunization extends Model
{
    public $pid;
    public $nk1=[];
    public $nk1_temp;
    public $vaccines=[];    
    public $temp_vaccine;
    public function saveVaccine(){
        array_push($this->vaccines,$this->temp_vaccine);
    }
    public function init()
    {
        $this->pid=new PidSegment();
        $this->nk1_temp=new Nk1Segment();
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function temp_Vaccine(){
        return $this->temp_vaccine;
    }
    public function saveNk1(){
        array_push($this->nk1,$this->nk1_temp);

    }
    /**
     * @inheritdoc
     */
    public function createVaccine(){
        $this->temp_vaccine=new Vaccines();
    }
    public function getPid(){
        return $this->hasProperty('pid');
    }
    /**
     * @inheritdoc
     */
    public function setnk1($nk1){
        array_push($this->nk1,$nk1);
    }
    public function generateMsg(){
        if(!$this->pid->validate()){
            throw new Exception(json_encode($this->pid->getErrors()));

        }
        $msg=$this->pid->generateString();
        $a=1;
        if(count($this->nk1)>0)
        foreach ($this->nk1 as $nk1){

            $msg.=$nk1->generateString($a);
            $a++;
        }
        if(count($this->vaccines)>0){
            for($i=0;$i<count($this->vaccines);$i++){
               
                $msg.=$this->vaccines[$i]->orc->generateString();
                $msg.=$this->vaccines[$i]->rxa->generateString();
                $msg.=$this->vaccines[$i]->rxr->generateString();
            }
        }
        return $msg;
    }
};